# Generated by Django 4.2.7 on 2024-04-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('abbreviated_title', models.CharField(max_length=150, verbose_name='Сокращенное наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(default='defauult.png', upload_to='medical_services/', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MedicalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Медицинская услуга')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('medical_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_services.medicalcategories', verbose_name='Категория мед.услуг')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
