# Generated by Django 4.2.7 on 2024-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=75, verbose_name='Телефон')),
                ('last_name', models.CharField(max_length=75, verbose_name='Имя пациента')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
            },
        ),
        migrations.CreateModel(
            name='MakeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('date_reception', models.DateTimeField(verbose_name='Дата и время приема')),
                ('anonymous_phone', models.CharField(blank=True, max_length=75, null=True, verbose_name='Телефон неавторизованного пользователя')),
                ('anonymous_first_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Имя неавторизованного пользователя')),
                ('anonymous_last_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Фамилия неавторизованного пользователя')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на приемы',
            },
        ),
    ]
