# Generated by Django 4.2.7 on 2024-04-19 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_services', '0001_initial'),
        ('users', '0001_initial'),
        ('registration_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makeappointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicalstaff', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='makeappointment',
            name='medical_services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_services.medicalservices', verbose_name='Медицинская услуга'),
        ),
        migrations.AddField(
            model_name='makeappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
    ]
