# Generated by Django 4.2.7 on 2024-04-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_services', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makeappointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
