# Generated by Django 4.2.7 on 2024-04-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_services', '0003_rename_doctor_id_makeappointment_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makeappointment',
            options={'ordering': ('date_reception',), 'verbose_name': 'Запись на прием', 'verbose_name_plural': 'Записи на приемы'},
        ),
    ]
