# Generated by Django 4.2.7 on 2024-04-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_services', '0004_alter_makeappointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backcall',
            options={'ordering': ('pk',), 'verbose_name': 'Обратный звонок', 'verbose_name_plural': 'Обратные звонки'},
        ),
    ]
